#!/usr/bin/env bash

set -e

command -v apt >/dev/null || {
  echo "require: apt" >&2
  exit 1
}

command -v gem >/dev/null || {
  echo "require: gem" >&2
  exit 1
}

[ -d "./src" ] || {
  # shellcheck disable=SC2016
  echo '"src" dir is missing' >&2
  exit 1
}

echo "[Install deps]"

echo "[curl,diffutils,jq]"
sudo apt install -y -qq curl diffutils jq

echo "[twurl]"

command -v twurl >/dev/null || {
  gem install -N -q twurl
  # shellcheck disable=SC2016
  echo 'run:`twurl authorize -u <NAME> -c <CK> -s <CS>`' >&2
  exit 1
}

[ -f "$HOME/.twurlrc" ] || {
  # shellcheck disable=SC2016
  echo 'run:`twurl authorize -u <NAME> -c <CK> -s <CS>`' >&2
  exit 1
}

d() {
  echo "[time]: $(LANG=en date +%Y-%m-%d\ %H:%M:%S.%N)"
}

echo "[Run]"

mkdir -p ../data

cp ./data/* ./src
cd ./src

d
echo "[get_authors]"
./get_authors | sed -u 's/$/&'$'\e\[A/' # ()->gem_authors.txt

d
echo "[get_letters]"
./get_letters | sed -u 's/$/&'$'\e\[A/' # ()->letters.csv

d
echo "[get_twitter_account]"
./get_twitter_account | sed -u 's/$/&'$'\e\[A/' # gem_authors.txt->twitters.csv

d
echo "[check_exist]"
./check_exist | sed -u 's/$/&'$'\e\[A/' # twitters.csv->exist.txt

d
echo "[add_gemdevs_list]"
./add_gemdevs_list | sed -u 's/$/&'$'\e\[A/' # twitters.csv,exist.txt->add.log

d
echo "[diff_lists_add_csv]"
./diff_lists_and_csv -y | sed -u 's/$/&'$'\e\[A/' # twitters.csv->list_members.json

mv deleted.txt exist.txt gem_authors.txt \
  letters.csv protected.txt twitters.csv add.log ../data
cd ..

d
echo "[done!]"
