#!/usr/bin/env bash

command -v curl >/dev/null || {
  echo "install: curl"
  exit 1
}

out="gem_authors.txt"
echo gem,name >"$out"
base="https://rubygems.org"
for l in {a..z}; do
  echo "[+]letter: $l"
  url="${base}/gems?letter=$l"
  last="$(
    curl -s "$url" | tac |
      grep -oPm1 '(?<=&amp;page=)\d+'
  )"
  gems=()
  for n in $(seq "$last"); do
    printf "[+]%04d/%04d pages\r" "$n" "$last"
    while IFS='' read -r line; do
      gem+=("$line")
    done < <(
      curl -s "${url}&page=${n}" |
        grep -oP '(?<=</a><a class="gems__gem" href=")/gems/.*(?=">)'
    )
  done
  echo
  i=0
  gems_len="${#gems[@]}"
  for g in "${gems[@]}"; do
    printf "[+]%04d/%04d gems\r" "$((i++))" "$gems_len"
    {
      curl -s "${base}${g}" |
        grep -oP '(?<=href=")/profiles/[^"]+(?=")'
    } | sed 's_^_https://rubygems.org_g' >>"$out"
  done
  echo
done
sort "$out" | uniq 1<>"$out"
echo "[+]done: $(wc <"$out" -l) authors have been found!"
