#!/usr/bin/env bash

command -v curl >/dev/null || {
  echo "install: curl"
  exit 1
}

out="${1-gem_authors.csv}"
echo gem,name > "$out"
base="https://rubygems.org"
for l in {a..z};{
  echo "[+]letter: $l"
  url="${base}/gems?letter=$l"
  last="$(
    curl -s "$url" | tac |
    grep -oPm1 '(?<=&amp;page=)\d+'
  )"
  gems=()
  for n in $(seq "$last");{
    printf "[+]%04d/%04d pages\r" "$n" "$last"
    gems+=($(
      curl -s "${url}&page=${n}"|
      grep -oP '(?<=</a><a class="gems__gem" href=")/gems/.*(?=">)'
    ))
  }
  echo
  i=0
  gems_len="${#gems[@]}"
  for g in "${gems[@]}";{
    printf "[+]%04d/%04d gems\r" "$((i++))" "$gems_len"
    {
      echo -n "${g},"
      curl -s "${base}${g}" |
      grep -oP '(?<=href="/profiles/)[^"]+(?=")'
    } >>"$out"
  }
  echo
}
echo "[+]done: authors have been found!"
