#!/usr/bin/env bash

command -v curl >/dev/null || {
  echo "install: curl"
  exit 1
}

[ -f "ua.txt" ] || {
  echo "ua.txt is not found." >&2
  exit 1
}

out="gem_authors.txt"
base="https://rubygems.org"
for l in {a..z}; do
  echo "[+]letter: $l"
  url="${base}/gems?letter=$l"
  last="$(
    curl -A "$(shuf -n1 ua.txt)" -s "$url" | tac |
      grep -oPm1 '(?<=&amp;page=)\d+'
  )"
  gems=()
  for n in $(seq "$last"); do
    printf "[+]%04d/%04d pages\r" "$n" "$last"
    while IFS=$'\n' read -r l; do
      gems+=("$l")
    done < <(
      curl -A "$(shuf -n1 ua.txt)" -s "${url}&page=${n}" |
        sed -nE '/class="gems__gem"/s_.*href="(/gems/[^"]+)">.*_\1_p'
    )
  done
  echo
  i=1
  gems_len="${#gems[@]}"
  for g in "${gems[@]}"; do
    printf "[+]%04d/%04d gems\r" "$i" "$gems_len"
    curl -A "$(shuf -n1 ua.txt)" -s "${base}${g}"  |
        sed -nE 's_.*href="(/profiles/[^"]+)".*_\1_p' \
        >>"$out"
    ((i++))
  done
  echo
done
sort "$out" | uniq | sed "s_^_https://rubygems.org_" >/tmp/_
mv /tmp/_ "$out"
au_len="$(wc <"$out" -l)"
echo "[+]done: ${au_len} authors have been found!"
