#!/usr/bin/env bash

command -v curl >/dev/null || {
  echo "install: curl" >&2
  exit 1
}

[ -f "ua.txt" ] || {
  echo "ua.txt is not found." >&2
  exit 1
}

out="${1-letters.csv}"
echo "letter,pages,gems" >"$out"
base="https://rubygems.org/gems?letter="
for i in {a..z}; do
  echo -n "${i}," | tee -a "$out"

  last="$(
    curl -A "$(shuf -n1 ua.txt)" -s "${base}${i}" |
      sed -nE 's/^.*page=([^"]+)">Last.*$/\1/p'
  )"
  echo -n "${last}," | tee -a "$out"

  last_gems="$(
    curl -A "$(shuf -n1 ua.txt)" -s "${base}${i}&page=${last}" |
      grep -c '"gems__gem"'
  )"
  bc <<<"$((last - 1))*30+${last_gems}" | tee -a "$out"
done

s="$(awk -F, 'NR>1{pages+=$2;gems+=$3}END{print "sum,"pages","gems}' "$out")"
echo "$s" >>"$out"

awk -F, '1<NR&&NR>27{a+=$3}END{print "Rubygems.org has "a" gems!"}' "$out"
